model:
  base_learning_rate: 4.5e-6
  target: asset.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 8192
    legacy: True
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0
      conv_type: PartialConv
      downsample_legacy: False
      norm_type: RegionNorm
    lossconfig:
      target: asset.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8
    train:
      target: asset.data.coco.CocoBase
      params:
        size: 296
        crop_size: 256
        random_crop: True
        dataroot: 'data/coco/imgs/train2017'
        datajson: 'data/coco/annotations/captions_train2017.json'
        seg_dir: 'data/coco/cocostuffthings/train2017'
        onehot_segmentation: True
        use_stuffthing: True
    validation:
      target: asset.data.coco.CocoBase
      params:
        size: 256
        crop_size: 256
        random_crop: False
        dataroot: 'data/coco/imgs/val2017'
        datajson: 'data/coco/annotations/captions_val2017.json'
        seg_dir: 'data/coco/cocostuffthings/val2017'
        onehot_segmentation: True
        use_stuffthing: True